# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-16 17:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0159_auto_20160614_2317'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActiviteTestimony',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('date_last_modif', models.DateTimeField(auto_now=True, verbose_name='Last changed')),
                ('date_v_debut', models.DateTimeField(default=django.utils.timezone.now, verbose_name='V. start')),
                ('date_v_fin', models.DateTimeField(blank=True, default=None, null=True, verbose_name='V. end')),
                ('testimony', models.TextField(blank=True, null=True, verbose_name='Testimony')),
                ('personne', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='personne_testimony', to='app.Personne')),
            ],
            options={
                'ordering': ['-date_last_modif'],
                'verbose_name': 'Activity / testimony',
                'verbose_name_plural': 'Activities / testimonies',
            },
        ),
        migrations.AlterModelOptions(
            name='activitecomments',
            options={'ordering': ['-date_last_modif'], 'verbose_name': 'Activity / comment', 'verbose_name_plural': 'Activities / comments'},
        ),
        migrations.AlterField(
            model_name='activitecomments',
            name='personne',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='personne_comment', to='app.Personne'),
        ),
        migrations.AddField(
            model_name='activite',
            name='testimony',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='activite', to='app.ActiviteTestimony'),
        ),
    ]
