# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-16 17:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0160_auto_20160616_1914'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activite',
            name='activite',
            field=models.IntegerField(choices=[(0, 'has a new relationship:'), (1, 'has a new travel:'), (2, "has changed a travel, it's now:"), (3, "Cogofly's news"), (4, 'has made a comment:'), (5, 'has made a testimony:')], default=0),
        ),
    ]
