# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-16 17:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0161_auto_20160616_1915'),
    ]

    operations = [
        migrations.AddField(
            model_name='activitetestimony',
            name='validated_by_moderator',
            field=models.BooleanField(default=False),
        ),
    ]
